### ISSUE TITLE
节点升级之后grpc-web 端口消失了

### ISSUE THREAD

**Issue by COLUD4** [Finschia/finschia#402]
Hello! After the node is upgraded to version v4.0.1, the grpc-web port disappears. How can I use the grpc-web port?

**Comment by tkxkd0159** [comment]
If you are node operator, you need to run [`envoy`](https://www.envoyproxy.io/docs/envoy/v1.31.0/configuration/http/http_filters/grpc_web_filter) proxy to support `grpc-web` from current version.
please refer this https://github.com/Finschia/finschia-sdk/pull/1418 if you need more detail.
